homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='homepage'),
	path('submit/', views.submit, name='submit'),
#	path('delete/<int:statusModel_id>/', views.deleteItem, name="delete")
	]
	

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

class statusModel(models.Model):
	status = models.CharField(max_length = 255)


	def __str__(self):
		return self.status

homepage/views.py
from django.shortcuts import render, redirect
from .models import statusModel
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
	status = statusModel.objects.all()
	content = { "statusList" : status }
	return render(request, 'homepage.html' , content)

@csrf_exempt
def submit(request):
		input_status = request.POST.get('status')
		newStatus = statusModel(status = input_status)
		newStatus.save()
		return redirect('homepage:homepage')
	
#def deleteItem(request, statusModel_id):
#    item = statusModel.objects.get(id=statusModel_id)
#    item.delete()
#    return redirect('homepage:homepage')

homepage/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset = "UTF-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
    <title>Story 6 Forms</title>
    <!-- Bootstrap CSS -->
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">
<style>
body{
background-color: gray;
}
</style>
</head>
<body>

    <form class="m-5" method="POST" action="{% url 'homepage:submit' %}">
        {% csrf_token %}
        <div class="container">
            <h2 style="text-align: center"> Hello,<br>How are you ?</h2>
            <div class="form-group">
                <label for='status'>Your status here :</label>
                <input type="text" class="form-control" id='status' name='status' placeholder="I'm having a blast!">
				<div class="container">
                <button type="submit" class="btn btn-primary" style="margin-top:10px">Submit</button>
				</div>
            </div>
        </div>
    </form>


	<div class="container">
          {% for statuses in statusList %}
			{% csrf_token %}
				<h4> {{ statuses.status }} </h4>
				<p><script> document.write(new Date().toDateString()); </script></p>

				<p><br><br></p>
			</form>
			{% endfor %}
      </div>


    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>